import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowRight,
  faBell,
  faCartShopping,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faClock,
  faEnvelope,
  faHeart,
  faLeaf,
  faLock,
  faMagnifyingGlass,
  faRefresh,
  faShieldHalved,
  faStore,
  faTriangleExclamation,
  faUserCircle,
  faUserShield,
} from '@fortawesome/free-solid-svg-icons';

export const appIcons: Record<string, IconDefinition> = {
  search: faMagnifyingGlass,
  cart: faCartShopping,
  notifications: faBell,
  account: faUserCircle,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronDown: faChevronDown,
  favorite: faHeart,
  checkCircle: faCheckCircle,
  email: faEnvelope,
  lock: faLock,
  eco: faLeaf,
  storefront: faStore,
  error: faTriangleExclamation,
  verify: faCircleCheck,
  arrowRight: faArrowRight,
  schedule: faClock,
  refresh: faRefresh,
  verifiedUser: faUserShield,
  shield: faShieldHalved,
};
